### ISSUE TITLE
How long wait updates?

### ISSUE THREAD

**Issue by Proha5** [TheLimePixel/GregBlock#126]
(bad english)
I start play the modpack. But i read "Issues", and see, that modpack have some critical bugs..
The modpack closed? or author plan to update? How long wait? I don't wish start modpack and stucked in future.

**Comment by Zixxl** [comment]
I've been playing it for a few weeks now and haven't encountered any problems. But it may be that sometimes you think there is bug because of the mechanics. For example, I built a basic extruder and thought I could use it to make iron rods (as it shows me JEI). But the mechanics are, that the recipie needs 48 EU/t and the "basic" machine only delivers 32 EU/t. So you need alt least an advanced extruder.
