### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by Grobes** [TheLimePixel/GregBlock#23]
Does it make any sense in progression and is it even possible to use the implosion compressor for making the AE2 singularities?

**Comment by TheLimePixel** [comment]
Technically that makes more sense for the Singularity Compressors, though that can't be done because unlike in AE2 you need to put all the items in the machine for the recipe to start. If you're talking about the Quantum Singularities, that can't be done because every pair of singularities has an id used to connect 2 quantum rings together.
