### ISSUE TITLE
Has anyone had server/setting up server issues?

### ISSUE THREAD

**Issue by Invalidm** [TheLimePixel/GregBlock#26]
For some reason every time I download the server files and try to run it. It doesn't seem to start and I can't seem to find the problem, I tried changing the server_start.bat to "minecraft_server" rather than the forge and all that did was give me a normal world. Let me know what I could do

**Comment by thaimichael** [comment]
Not sure what your issue is but you have no real details in your dialog here.

These are the steps I performed to test had no issues with the latest client
1. OS Windows 10 64bit
2. Java Version 1.8.0.181 (64bit)
3. Downloaded and extracted to a folder GregBlock-1.1.3+Server+File
4. ran start.bat
5. Joy server started up in about 5 minutes with the console window open ready to accept clients on the standard port and IP address of the machine with the server running.
6. Started game client input IP address of server machine connected with no issues.
