### ISSUE TITLE
[Suggestion] Use Iron Chests mod

### ISSUE THREAD

**Issue by Insane96** [TheLimePixel/GregBlock#91]
Gregtech chests are really bad:
- Have no opening animation and sound
- Content cannot be ordered
- They can't be picked up with carry on

I would suggest using Iron Chests mod (should have even bronze chests, etc) and removing the unwaned chests.

**Comment by TheLimePixel** [comment]
Though I'm assuming your real main problem is that they don't store a lot, which is why I myself implemented Crates. And even if we did have Iron Chests you wouldn't be able to carry them. Most modded inventories are exploitable on servers and it's a general fact that on expert packs people tend to use as many exploits as possible. The sorting will be fixed eventually.

**Comment by RobertLSnead** [comment]
Hoping the sorting fix is resolved soon! : D
Love the pack by the way!
